
spring:
  thymeleaf:
    cache: false # 关闭缓存, 调试用
  session:
    store-type: redis  # 会话存储类型
    redis:
      flush-mode: on_save # # 会话刷新模式
      namespace: spring:session # 用于存储会话的键的命名空间
  redis:
    host: ubuntu
    port: 6379
  # RabbitMQ配置
  rabbitmq:
    host: ubuntu
    port: 5672
    username: guest
    password: guest
    virtual-host: / # 虚拟主机配置
    publisher-confirm-type: correlated # 开启发送端消息抵达Broker确认
    publisher-returns: true # 开启发送端消息抵达Queue确认
    template:
      mandatory: true # 只要消息抵达Queue，就会异步发送优先回调returnfirm
    listener:
      simple:
        acknowledge-mode: manual  # 手动ack消息，不使用默认的消费端确认
      type: simple # 默认值

server:
  servlet:
    session:
      timeout: 30m # 会话超时 如果未指定持续时间后缀，则使用秒

# 日志级别
logging:
  level:
    com.imgyh.mall: debug